"""Sample data to simulate software listings"""

software_repository = [
    {
        "name": "RobotControlApp",
        "version": "1.0.0",
        "author": "Robotics Inc.",
        "description": "Control application for robotic arms.",
        "compatibility": ["R1000", "TB200"],
        "license": "MIT License",
        "documentation_url": "https://example.com/robotcontrolapp-docs",
    },
    {
        "name": "VisionProcessing",
        "version": "2.1.0",
        "author": "VisionTech Corp.",
        "description": "Computer vision processing software for robots.",
        "compatibility": ["RT3000"],
        "license": "Apache License 2.0",
        "documentation_url": "https://example.com/visionprocessing-docs",
    },
    {
        "name": "RobotSimulator",
        "version": "3.5.2",
        "author": "SimuRobotics LLC",
        "description": "Simulation software for testing robot behaviors.",
        "compatibility": ["R1000", "TB200", "RT3000"],
        "license": "GNU GPL v3",
        "documentation_url": "https://example.com/robotsimulator-docs",
    },
    {
        "name": "MotionControlApp",
        "version": "2.0.1",
        "author": "Robotics Inc.",
        "description": "Advanced motion control software for robotic systems.",
        "compatibility": ["R1000", "TB200", "AI9000"],
        "license": "Apache License 2.0",
        "documentation_url": "https://example.com/motioncontrolapp-docs",
    },
    {
        "name": "RobotVisionAI",
        "version": "1.5.0",
        "author": "AI VisionTech",
        "description": "Artificial intelligence-based vision processing software for robots.",
        "compatibility": ["RT3000", "INNO-X5"],
        "license": "MIT License",
        "documentation_url": "https://example.com/robotvisionai-docs",
    },
    {
        "name": "RoboticsSimSuite",
        "version": "4.0.3",
        "author": "SimuRobotics LLC",
        "description": "Comprehensive simulation suite for robot testing and development.",
        "compatibility": ["R1000", "AI9000", "INNO-X5"],
        "license": "GNU GPL v3",
        "documentation_url": "https://example.com/roboticssimsuite-docs",
    },
    {
        "name": "RobotControlPro",
        "version": "3.2.1",
        "author": "RoboTech Systems",
        "description": "Professional robot control software for industrial applications.",
        "compatibility": ["AI9000", "INNO-X5"],
        "license": "Proprietary",
        "documentation_url": "https://example.com/robotcontrolpro-docs",
    },
    {
        "name": "InnoBoticsAI",
        "version": "2.1.2",
        "author": "InnoBotics",
        "description": "AI-driven software for Inno-X5 robot optimization.",
        "compatibility": ["R1000"],
        "license": "MIT License",
        "documentation_url": "https://example.com/innoboticsai-docs",
    },
]