name: the_construct
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Auth
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0

  #Data
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #Firebase
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_storage: ^11.2.4
  
  # Firebase Web
  cloud_firestore_web: ^3.6.2
  firebase_analytics_web: ^0.5.4+3
  firebase_auth_web: ^5.5.3
  firebase_core_web: ^2.6.0
  firebase_storage_web: ^3.6.4

  #Networking
  http: ^1.1.0
  url_launcher: ^6.1.7

  # State Management
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  observable: ^0.24.0

  #UI
  curved_navigation_bar: ^1.0.3
  google_fonts: ^5.1.0
  responsive_framework: ^1.1.0
  flutter_neumorphic: ^3.2.0
  flex_color_scheme: ^7.1.2
  expandable: ^5.0.1
  nil: ^1.1.1
  showcaseview: ^2.0.0+1
  styled_widget: ^0.4.1
  fade_shimmer: ^2.2.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^22.1.36

  #Misc
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  go_router: ^9.0.0
  shared_preferences: ^2.2.0
  flutter_tts: ^3.6.3
  mockito: ^5.4.0
  flutter_spinkit: ^5.2.0
  easy_search_bar: ^2.5.0
  flutter_svg: ^2.0.7
  web3dart: ^2.7.1
  flutter_web3: ^2.1.9
  js: ^0.6.7

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  go_router_builder: ^2.2.0
  build_verify: ^3.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/launch_screen.png
